### ISSUE TITLE
Adding typ for JWT Header 

### ISSUE THREAD

**Issue by laisee** [sopium/jwtk#10]
JWT header field 'alg' is set automatically when creating Header (or HeaderAndClaims). How to assign a value to the "typ" field, or better yet have a a default value assigned? Fairly new to Rust and looked through sample code but it only shows the headerAndClaims being set before signing (EC256).

**Comment by blckngm** [comment]
If `claims` is `HeaderAndClaims`, just `claims.headers_mut().typ = Some("some-typ".to_string())`.

**Comment by laisee** [comment]
Thanks! Bit new to Rust syntax ...

I added the assignment for "typ" to the end of some other claims assignments and it worked.

```
claims
        .set_iat_now()
        .set_exp_from_now(Duration::from_secs(18000))
        .insert("client", "api")
        .insert("uri", uri)
        .insert("nonce", now)
        .insert("sub", "user-account-id")
        .header_mut().typ =Some("JWT".to_string()); 
```
