### ISSUE TITLE
Add more header options

### ISSUE THREAD

**Issue by theaddonn** [sopium/jwtk#6]
jwt headers should have more options like: `cty`, `jku`, `jwk`, `x5u`, `x5c`, `x5c` etc..
This would be very helpful.

**Comment by blckngm** [comment]
There is [`extra`](https://docs.rs/jwtk/latest/jwtk/struct.Header.html#structfield.extra) in the header struct for these fields. Does this work for your use case?

**Comment by theaddonn** [comment]
oh really nice to see that, thanks!

**Comment by theaddonn** [comment]
(adding a notice to this in the source code would be awesome)
